# AUTOGENERATED! DO NOT EDIT! File to edit: app.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'examples', 'intf', 'get_x', 'classify_imgs']

# %% app.ipynb 1
from fastai.vision.all import *
import gradio as gr

# %% app.ipynb 4
def get_x(row):
    idx = row['idx']
    img_pix = trn_x[idx]
    img_pix = np.stack([img_pix]*3, axis=-1)
    return PILImage.create(img_pix.astype(np.uint8))

# %% app.ipynb 5
learn = load_learner('model.pkl')

# %% app.ipynb 7
categories = [str(i) for i in range(20)]
categories = tuple(categories)

def classify_imgs(x):
    pred,idx,probs = learn.predict(x)
    return dict(zip(categories,probs))

# %% app.ipynb 9
examples = [np.load('img1.npy'), np.load('img2.npy'), np.load('img3.npy'), np.load('img4.npy'), np.load('img5.npy')]

intf = gr.Interface(fn=classify_imgs, inputs=gr.Image(), outputs=gr.Label(), examples=examples)
intf.launch(inline=False)
